name: Continuous Integration - Audit (Terraform)

on:
  workflow_call:

concurrency:
  group: audit-terraform-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  terraform-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Brioche
        uses: brioche-dev/setup-brioche@9b82d4ee697500f7d81f6397a943935ffa3d887b # v1.5.0

      - name: Install trivy
        run: brioche install -r trivy

      - name: Run security scanner
        run: trivy conf --severity HIGH,CRITICAL .
