name: Continuous Integration - Audit (Terraform)

on:
  workflow_call:

concurrency:
  group: audit-terraform-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  terraform-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Brioche
        uses: brioche-dev/setup-brioche@9b82d4ee697500f7d81f6397a943935ffa3d887b # v1.5.0

      - name: Install trivy
        run: brioche install -r trivy

      - name: Run security scanner
        run: trivy conf --severity HIGH,CRITICAL .
