name: Continuous Integration - Build (Zine)

on:
  workflow_call:
    inputs:
      zine-version:
        description: "Zine release tag to install via kristoff-it/setup-zine."
        type: string
        required: true

concurrency:
  group: build-zine-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  zine-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Zine
        uses: kristoff-it/setup-zine@ecfe04402bfa943fb0dc59e097e81c858a8ad9d9 # v2
        with:
          version: ${{ inputs.zine-version }}

      - name: Build
        run: zine release
