name: Continuous Integration - Static Analysis (Terraform)

on:
  workflow_call:

concurrency:
  group: static-analysis-terraform-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  terraform-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Brioche
        uses: brioche-dev/setup-brioche@9b82d4ee697500f7d81f6397a943935ffa3d887b # v1.5.0

      - name: Install Terraform
        run: brioche install -r terraform

      - name: Check formatting
        run: terraform fmt -check -recursive -write=false -diff

  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Brioche
        uses: brioche-dev/setup-brioche@9b82d4ee697500f7d81f6397a943935ffa3d887b # v1.5.0

      - name: Install tflint
        run: brioche install -r tflint

      - name: Check linting
        run: tflint --recursive
